# Generated by Django 4.0.6 on 2023-09-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('act_fecha', models.DateField()),
                ('act_descripcion', models.CharField(max_length=30)),
                ('act_cupo', models.IntegerField()),
                ('act_imagen', models.CharField(max_length=300)),
                ('act_cuota', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('adm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adm_nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('asis_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('cer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cer_nombre', models.IntegerField()),
            ],
            options={
                'db_table': 'certificado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuotaSocial',
            fields=[
                ('cuo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuo_monto', models.IntegerField()),
                ('cuo_fecha_pago', models.DateField()),
                ('cuo_estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cuota_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('esp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('esp_nombre', models.CharField(max_length=30)),
                ('esp_direccion', models.CharField(max_length=50)),
                ('esp_telefono', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'espacio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('est_proy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('est_proy_estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliarMiembro',
            fields=[
                ('fam_mie_rut', models.IntegerField(primary_key=True, serialize=False)),
                ('mie_dv', models.CharField(max_length=1)),
                ('mie_nombre', models.CharField(max_length=30)),
                ('mie_ap_paterno', models.CharField(max_length=30)),
                ('mie_ap_materno', models.CharField(max_length=30)),
                ('mie_telefono', models.CharField(max_length=12)),
                ('parentesco', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'familiar_miembro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JuntaVecinos',
            fields=[
                ('jun_id', models.IntegerField(primary_key=True, serialize=False)),
                ('jun_nombre', models.CharField(max_length=50)),
                ('jun_fecha_fundacion', models.DateField()),
                ('jun_nombre_villa', models.CharField(max_length=30)),
                ('jun_telefono', models.CharField(max_length=12, unique=True)),
                ('jun_correo', models.CharField(max_length=50, unique=True)),
                ('jun_direccion', models.CharField(max_length=50)),
                ('jun_mision', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'junta_vecinos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('mie_rut', models.IntegerField(primary_key=True, serialize=False)),
                ('mie_dv', models.CharField(max_length=1)),
                ('mie_nombre', models.CharField(max_length=30)),
                ('mie_ap_paterno', models.CharField(max_length=30)),
                ('mie_ap_materno', models.CharField(max_length=30)),
                ('mie_fecha_nacimento', models.DateField()),
                ('mie_telefono', models.CharField(max_length=12, unique=True)),
                ('mie_correo', models.CharField(max_length=50, unique=True)),
                ('mie_password', models.CharField(max_length=50)),
                ('mie_direccion', models.CharField(max_length=30)),
                ('mie_estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'miembro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('not_id', models.IntegerField(primary_key=True, serialize=False)),
                ('not_titulo', models.CharField(max_length=50)),
                ('not_subtitulo', models.CharField(max_length=100)),
                ('not_fecha', models.DateField()),
                ('not_descripcion', models.CharField(max_length=300)),
                ('not_imagen', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'noticia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('proy_nombre', models.CharField(max_length=30)),
                ('proy_descripcion', models.CharField(max_length=300)),
                ('proy_imagen', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reg_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('res_id', models.IntegerField(primary_key=True, serialize=False)),
                ('res_fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudCertificado',
            fields=[
                ('sol_cer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sol_cer_fecha', models.DateField()),
            ],
            options={
                'db_table': 'solicitud_certificado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('tip_act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tip_act_nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_actividad',
                'managed': False,
            },
        ),
    ]
