# Generated by Django 4.0.6 on 2023-09-27 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_fecha', models.DateField()),
                ('act_descripcion', models.CharField(max_length=30)),
                ('act_cupo', models.IntegerField()),
                ('act_imagen', models.CharField(max_length=300)),
                ('act_cuota', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('cer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cer_nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('esp_id', models.AutoField(primary_key=True, serialize=False)),
                ('esp_nombre', models.CharField(max_length=30)),
                ('esp_direccion', models.CharField(max_length=50)),
                ('esp_telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('est_proy_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_proy_estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JuntaVecinos',
            fields=[
                ('jun_id', models.AutoField(primary_key=True, serialize=False)),
                ('jun_nombre', models.CharField(max_length=50)),
                ('jun_fecha_fundacion', models.DateField()),
                ('jun_nombre_villa', models.CharField(max_length=30)),
                ('jun_telefono', models.CharField(max_length=12, unique=True)),
                ('jun_correo', models.CharField(max_length=50, unique=True)),
                ('jun_direccion', models.CharField(max_length=50)),
                ('jun_mision', models.CharField(max_length=300)),
                ('comuna_com', models.ForeignKey(db_column='COMUNA_com_id', on_delete=django.db.models.deletion.PROTECT, to='principal.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('mie_rut', models.IntegerField(primary_key=True, serialize=False)),
                ('mie_dv', models.CharField(max_length=1)),
                ('mie_nombre', models.CharField(max_length=30)),
                ('mie_ap_paterno', models.CharField(max_length=30)),
                ('mie_ap_materno', models.CharField(max_length=30)),
                ('mie_fecha_nacimento', models.DateField()),
                ('mie_telefono', models.CharField(max_length=12, unique=True)),
                ('mie_correo', models.CharField(max_length=50, unique=True)),
                ('mie_password', models.CharField(max_length=150)),
                ('mie_direccion', models.CharField(max_length=50)),
                ('mie_estado', models.CharField(max_length=30)),
                ('cargo_car', models.ForeignKey(db_column='CARGO_car_id', on_delete=django.db.models.deletion.PROTECT, to='principal.cargo')),
                ('junta_vecinos_jun', models.ForeignKey(db_column='JUNTA_VECINOS_jun_id', on_delete=django.db.models.deletion.PROTECT, to='principal.juntavecinos')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('tip_act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tip_act_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCertificado',
            fields=[
                ('sol_cer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sol_cer_fecha', models.DateField()),
                ('certificado_cer', models.ForeignKey(db_column='CERTIFICADO_cer_id', on_delete=django.db.models.deletion.PROTECT, to='principal.certificado')),
                ('miembro_mie_rut', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_fecha_hora', models.DateTimeField()),
                ('espacio_esp', models.ForeignKey(db_column='ESPACIO_esp_id', on_delete=django.db.models.deletion.PROTECT, to='principal.espacio')),
                ('miembro_mie_rut', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proy_id', models.AutoField(primary_key=True, serialize=False)),
                ('proy_nombre', models.CharField(max_length=30)),
                ('proy_descripcion', models.CharField(max_length=300)),
                ('proy_imagen', models.CharField(max_length=300)),
                ('estado_proyecto_est_proy', models.ForeignKey(db_column='ESTADO_PROYECTO_est_proy_id', on_delete=django.db.models.deletion.PROTECT, to='principal.estadoproyecto')),
                ('miembro_mie_rut', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('not_titulo', models.CharField(max_length=50)),
                ('not_subtitulo', models.CharField(max_length=100)),
                ('not_fecha', models.DateField()),
                ('not_descripcion', models.CharField(max_length=300)),
                ('not_imagen', models.CharField(max_length=300)),
                ('actividad_act', models.ForeignKey(blank=True, db_column='ACTIVIDAD_act_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='principal.actividad')),
                ('miembro_mie_rut', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
                ('proyecto_proy', models.ForeignKey(blank=True, db_column='PROYECTO_proy_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='principal.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliarMiembro',
            fields=[
                ('fam_mie_rut', models.IntegerField(primary_key=True, serialize=False)),
                ('mie_dv', models.CharField(max_length=1)),
                ('mie_nombre', models.CharField(max_length=30)),
                ('mie_ap_paterno', models.CharField(max_length=30)),
                ('mie_ap_materno', models.CharField(max_length=30)),
                ('mie_telefono', models.CharField(max_length=12)),
                ('parentesco', models.CharField(max_length=30)),
                ('miembro_mie_rut', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
        migrations.AddField(
            model_name='espacio',
            name='junta_vecinos_jun',
            field=models.ForeignKey(db_column='JUNTA_VECINOS_jun_id', on_delete=django.db.models.deletion.PROTECT, to='principal.juntavecinos'),
        ),
        migrations.CreateModel(
            name='CuotaSocial',
            fields=[
                ('cuo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuo_monto', models.IntegerField()),
                ('cuo_fecha_pago', models.DateField()),
                ('cuo_estado', models.CharField(max_length=30)),
                ('miembro_mie_rut', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region_reg',
            field=models.ForeignKey(db_column='REGION_reg_id', on_delete=django.db.models.deletion.PROTECT, to='principal.region'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('asis_id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_act', models.ForeignKey(db_column='ACTIVIDAD_act_id', on_delete=django.db.models.deletion.PROTECT, to='principal.actividad')),
                ('miembro_mie_rut', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad_tip_act',
            field=models.ForeignKey(db_column='TIPO_ACTIVIDAD_tip_act_id', on_delete=django.db.models.deletion.PROTECT, to='principal.tipoactividad'),
        ),
    ]
