# Generated by Django 4.0.6 on 2023-09-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='mie_fecha_nacimento',
            new_name='mie_fecha_nacimiento',
        ),
    ]
