# Generated by Django 4.0.6 on 2023-09-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_rename_mie_ap_materno_familiarmiembro_fam_mie_ap_materno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='miembro_mie_rut',
            new_name='miembro_mie',
        ),
        migrations.RenameField(
            model_name='cuotasocial',
            old_name='miembro_mie_rut',
            new_name='miembro_mie',
        ),
        migrations.RenameField(
            model_name='espacio',
            old_name='junta_vecinos_jun',
            new_name='junta_vecinos',
        ),
        migrations.RenameField(
            model_name='familiarmiembro',
            old_name='miembro_mie_rut',
            new_name='miembro_mie',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='miembro_mie_rut',
            new_name='miembro_mie',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='miembro_mie_rut',
            new_name='miembro_mie',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='miembro_mie_rut',
            new_name='miembro_mie',
        ),
        migrations.RenameField(
            model_name='solicitudcertificado',
            old_name='miembro_mie_rut',
            new_name='miembro_mie',
        ),
    ]
