# Generated by Django 4.0.6 on 2023-10-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_rename_miembro_mie_rut_asistencia_miembro_mie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcertificado',
            name='certificado_cer',
        ),
        migrations.RemoveField(
            model_name='solicitudcertificado',
            name='miembro_mie',
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='tip_act_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Certificado',
        ),
        migrations.DeleteModel(
            name='SolicitudCertificado',
        ),
    ]
