# Generated by Django 4.0.6 on 2023-10-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_remove_solicitudcertificado_certificado_cer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('cer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cer_nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCertificado',
            fields=[
                ('sol_cer_id', models.AutoField(primary_key=True, serialize=False)),
                ('sol_cer_fecha', models.DateField(auto_now_add=True)),
                ('certificado_cer', models.ForeignKey(db_column='CERTIFICADO_cer_id', on_delete=django.db.models.deletion.PROTECT, to='principal.certificado')),
                ('miembro_mie', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
    ]
