# Generated by Django 4.0.6 on 2023-10-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_certificado_solicitudcertificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='proy_imagen',
            field=models.ImageField(upload_to='media/proyecto/'),
        ),
    ]
