# Generated by Django 4.0.6 on 2023-10-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_miembro_mie_firma_alter_espacio_esp_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='mie_firma',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
