# Generated by Django 4.0.6 on 2023-10-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_alter_espacio_esp_imagen_alter_miembro_mie_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcertificado',
            name='sol_cer_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudcertificado',
            name='sol_cer_rut_familiar',
            field=models.IntegerField(null=True),
        ),
    ]
