# Generated by Django 4.0.6 on 2023-10-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_solicitudcertificado_sol_cer_familiar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='esp_imagen',
            field=models.ImageField(null=True, upload_to='media/espacio/'),
        ),
    ]
