# Generated by Django 4.0.6 on 2023-10-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_alter_espacio_esp_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacio',
            old_name='junta_vecinos',
            new_name='junta_vecinos_jun',
        ),
    ]
