# Generated by Django 4.0.6 on 2023-10-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_rename_junta_vecinos_espacio_junta_vecinos_jun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
