# Generated by Django 4.0.6 on 2023-10-17 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_fecha', models.DateField()),
                ('res_hora_inicio', models.TimeField()),
                ('res_hora_fin', models.TimeField()),
                ('espacio_esp', models.ForeignKey(db_column='ESPACIO_esp_id', on_delete=django.db.models.deletion.PROTECT, to='principal.espacio')),
                ('miembro_mie', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
    ]
