# Generated by Django 4.0.6 on 2023-10-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='actividad_act',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='proyecto_proy',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='not_fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='not_imagen',
            field=models.ImageField(null=True, upload_to='media/noticia/'),
        ),
    ]
