# Generated by Django 4.0.6 on 2023-10-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_remove_noticia_actividad_act_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='mie_estado',
        ),
        migrations.AddField(
            model_name='juntavecinos',
            name='jun_certificado_vigencia',
            field=models.ImageField(blank=True, upload_to='media/juntaVecinos/'),
        ),
        migrations.AddField(
            model_name='juntavecinos',
            name='jun_directiva',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='juntavecinos',
            name='jun_habilitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juntavecinos',
            name='jun_rol_municipal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juntavecinos',
            name='jun_mision',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
