# Generated by Django 4.0.6 on 2023-11-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_miembro_mie_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='act_imagen',
        ),
        migrations.AlterField(
            model_name='juntavecinos',
            name='jun_correo',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='juntavecinos',
            name='jun_directiva',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='juntavecinos',
            name='jun_rol_municipal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='mie_correo',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
