# Generated by Django 4.0.6 on 2023-11-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_remove_actividad_act_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='actividad_act',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='miembro_mie',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
