# Generated by Django 4.0.6 on 2023-11-07 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_remove_asistencia_actividad_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_fecha', models.DateField()),
                ('act_descripcion', models.CharField(max_length=30)),
                ('act_cupo', models.IntegerField()),
                ('act_cuota', models.IntegerField(default=0, null=True)),
                ('junta_vecinos_jun', models.ForeignKey(db_column='JUNTA_VECINOS_jun_id', on_delete=django.db.models.deletion.PROTECT, to='principal.juntavecinos')),
                ('tipo_actividad_tip_act', models.ForeignKey(db_column='TIPO_ACTIVIDAD_tip_act_id', on_delete=django.db.models.deletion.PROTECT, to='principal.tipoactividad')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('asis_id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_act', models.ForeignKey(db_column='ACTIVIDAD_act_id', on_delete=django.db.models.deletion.PROTECT, to='principal.actividad')),
                ('miembro_mie', models.ForeignKey(db_column='MIEMBRO_mie_rut', on_delete=django.db.models.deletion.PROTECT, to='principal.miembro')),
            ],
        ),
    ]
