# Generated by Django 4.0.6 on 2023-11-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_actividad_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asis_cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
