CREATE TABLE `ACTIVIDAD` (
  `act_id` INTEGER NOT NULL AUTO_INCREMENT,
  `act_fecha` DATE NOT NULL,
  `act_descripcion` VARCHAR(30) NOT NULL,
  `act_cupo` INTEGER NOT NULL,
  `act_imagen` VARCHAR(300) NOT NULL,
  `act_cuota` INTEGER,
  `TIPO_ACTIVIDAD_tip_act_id` INTEGER NOT NULL,
  PRIMARY KEY (`act_id`)
);

CREATE TABLE `ASISTENCIA` (
  `asis_id` INTEGER NOT NULL AUTO_INCREMENT,
  `ACTIVIDAD_act_id` INTEGER NOT NULL,
  `MIEMBRO_mie_rut` INTEGER NOT NULL,
  PRIMARY KEY (`asis_id`)
);

CREATE TABLE `CARGO` (
  `car_id` INTEGER NOT NULL AUTO_INCREMENT,
  `car_nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`car_id`)
);

CREATE TABLE `CERTIFICADO` (
  `cer_id` INTEGER NOT NULL AUTO_INCREMENT,
  `cer_nombre` INTEGER NOT NULL,
  PRIMARY KEY (`cer_id`)
);

CREATE TABLE `COMUNA` (
  `com_id` INTEGER NOT NULL AUTO_INCREMENT,
  `com_nombre` VARCHAR(30) NOT NULL,
  `REGION_reg_id` INTEGER NOT NULL,
  PRIMARY KEY (`com_id`)
);

CREATE TABLE `CUOTA_SOCIAL` (
  `cuo_id` INTEGER NOT NULL AUTO_INCREMENT,
  `cuo_monto` INTEGER NOT NULL,
  `cuo_fecha_pago` DATE NOT NULL,
  `cuo_estado` VARCHAR(30) NOT NULL,
  `MIEMBRO_mie_rut` INTEGER NOT NULL,
  PRIMARY KEY (`cuo_id`)
);

CREATE TABLE `ESPACIO` (
  `esp_id` INTEGER NOT NULL AUTO_INCREMENT,
  `esp_nombre` VARCHAR(30) NOT NULL,
  `esp_direccion` VARCHAR(50) NOT NULL,
  `esp_telefono` VARCHAR(12) NOT NULL,
  `JUNTA_VECINOS_jun_id` INTEGER NOT NULL,
  PRIMARY KEY (`esp_id`)
);

CREATE TABLE `ESTADO_PROYECTO` (
  `est_proy_id` INTEGER NOT NULL AUTO_INCREMENT,
  `est_proy_estado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`est_proy_id`)
);

CREATE TABLE `FAMILIAR_MIEMBRO` (
  `fam_mie_rut` INTEGER NOT NULL,
  `mie_dv` CHAR NOT NULL,
  `mie_nombre` VARCHAR(30) NOT NULL,
  `mie_ap_paterno` VARCHAR(30) NOT NULL,
  `mie_ap_materno` VARCHAR(30) NOT NULL,
  `mie_telefono` VARCHAR(12) NOT NULL,
  `parentesco` VARCHAR(30) NOT NULL,
  `MIEMBRO_mie_rut` INTEGER NOT NULL,
  PRIMARY KEY (`fam_mie_rut`)
);

CREATE TABLE `JUNTA_VECINOS` (
  `jun_id` INTEGER NOT NULL AUTO_INCREMENT,
  `jun_nombre` VARCHAR(50) NOT NULL,
  `jun_fecha_fundacion` DATE NOT NULL,
  `jun_nombre_villa` VARCHAR(30) NOT NULL,
  `jun_telefono` VARCHAR(12) NOT NULL,
  `jun_correo` VARCHAR(50) NOT NULL,
  `jun_direccion` VARCHAR(50) NOT NULL,
  `jun_mision` VARCHAR(300) NOT NULL,
  `COMUNA_com_id` INTEGER NOT NULL,
  PRIMARY KEY (`jun_id`)
);

CREATE TABLE `MIEMBRO` (
  `mie_rut` INTEGER NOT NULL,
  `mie_dv` CHAR(1) NOT NULL,
  `mie_nombre` VARCHAR(30) NOT NULL,
  `mie_ap_paterno` VARCHAR(30) NOT NULL,
  `mie_ap_materno` VARCHAR(30) NOT NULL,
  `mie_fecha_nacimento` DATE NOT NULL,
  `mie_telefono` VARCHAR(12) NOT NULL,
  `mie_correo` VARCHAR(50) NOT NULL,
  `mie_password` VARCHAR(50) NOT NULL,
  `mie_direccion` VARCHAR(30) NOT NULL,
  `JUNTA_VECINOS_jun_id` INTEGER NOT NULL,
  `mie_estado` VARCHAR(30) NOT NULL DEFAULT "Inhabilitado",
  `CARGO_car_id` INTEGER NOT NULL,
  PRIMARY KEY (`mie_rut`)
);

CREATE TABLE `NOTICIA` (
  `not_id` INTEGER NOT NULL AUTO_INCREMENT,
  `not_titulo` VARCHAR(50) NOT NULL,
  `not_subtitulo` VARCHAR(100) NOT NULL,
  `not_fecha` DATE NOT NULL,
  `not_descripcion` VARCHAR(300) NOT NULL,
  `not_imagen` VARCHAR(300) NOT NULL,
  `ACTIVIDAD_act_id` INTEGER,
  `PROYECTO_proy_id` INTEGER,
  `MIEMBRO_mie_rut` INTEGER NOT NULL,
  PRIMARY KEY (`not_id`)
);

CREATE TABLE `PROYECTO` (
  `proy_id` INTEGER NOT NULL AUTO_INCREMENT,
  `proy_nombre` VARCHAR(30) NOT NULL,
  `proy_descripcion` VARCHAR(300) NOT NULL,
  `proy_imagen` VARCHAR(300) NOT NULL,
  `ESTADO_PROYECTO_est_proy_id` INTEGER NOT NULL,
  `MIEMBRO_mie_rut` INTEGER NOT NULL,
  PRIMARY KEY (`proy_id`)
);

CREATE TABLE `REGION` (
  `reg_id` INTEGER NOT NULL AUTO_INCREMENT,
  `reg_nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`reg_id`)
);

CREATE TABLE `RESERVA` (
  `res_id` INTEGER NOT NULL AUTO_INCREMENT,
  `res_fecha_hora` DATETIME NOT NULL DEFAULT (now()),
  `MIEMBRO_mie_rut` INTEGER NOT NULL,
  `ESPACIO_esp_id` INTEGER NOT NULL,
  PRIMARY KEY (`res_id`)
);

CREATE TABLE `SOLICITUD_CERTIFICADO` (
  `sol_cer_id` INTEGER NOT NULL,
  `sol_cer_fecha` DATE NOT NULL,
  `MIEMBRO_mie_rut` INTEGER NOT NULL,
  `CERTIFICADO_cer_id` INTEGER NOT NULL,
  PRIMARY KEY (`sol_cer_id`)
);

CREATE TABLE `TIPO_ACTIVIDAD` (
  `tip_act_id` INTEGER NOT NULL,
  `tip_act_nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`tip_act_id`)
);

CREATE UNIQUE INDEX `JUNTA_VECINOS_jun_telefono_UN` ON `JUNTA_VECINOS` (`jun_telefono`);

CREATE UNIQUE INDEX `JUNTA_VECINOS_jun_correo_UN` ON `JUNTA_VECINOS` (`jun_correo`);

CREATE UNIQUE INDEX `MIEMBRO_mie_telefono_UN` ON `MIEMBRO` (`mie_telefono`);

CREATE UNIQUE INDEX `MIEMBRO_mie_correo_UN` ON `MIEMBRO` (`mie_correo`);

ALTER TABLE `ACTIVIDAD` ADD CONSTRAINT `ACTIVIDAD_TIPO_ACTIVIDAD_FK` FOREIGN KEY (`TIPO_ACTIVIDAD_tip_act_id`) REFERENCES `TIPO_ACTIVIDAD` (`tip_act_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `ASISTENCIA` ADD CONSTRAINT `ASISTENCIA_ACTIVIDAD_FK` FOREIGN KEY (`ACTIVIDAD_act_id`) REFERENCES `ACTIVIDAD` (`act_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `ASISTENCIA` ADD CONSTRAINT `ASISTENCIA_MIEMBRO_FK` FOREIGN KEY (`MIEMBRO_mie_rut`) REFERENCES `MIEMBRO` (`mie_rut`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `COMUNA` ADD CONSTRAINT `COMUNA_REGION_FK` FOREIGN KEY (`REGION_reg_id`) REFERENCES `REGION` (`reg_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `CUOTA_SOCIAL` ADD CONSTRAINT `CUOTA_SOCIAL_MIEMBRO_FK` FOREIGN KEY (`MIEMBRO_mie_rut`) REFERENCES `MIEMBRO` (`mie_rut`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `ESPACIO` ADD CONSTRAINT `ESPACIO_JUNTA_VECINOS_FK` FOREIGN KEY (`JUNTA_VECINOS_jun_id`) REFERENCES `JUNTA_VECINOS` (`jun_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `FAMILIAR_MIEMBRO` ADD CONSTRAINT `FAMILIAR_MIEMBRO_MIEMBRO_FK` FOREIGN KEY (`MIEMBRO_mie_rut`) REFERENCES `MIEMBRO` (`mie_rut`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `JUNTA_VECINOS` ADD CONSTRAINT `JUNTA_VECINOS_COMUNA_FK` FOREIGN KEY (`COMUNA_com_id`) REFERENCES `COMUNA` (`com_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `MIEMBRO` ADD CONSTRAINT `MIEMBRO_CARGO_FK` FOREIGN KEY (`CARGO_car_id`) REFERENCES `CARGO` (`car_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `MIEMBRO` ADD CONSTRAINT `MIEMBRO_JUNTA_VECINOS_FK` FOREIGN KEY (`JUNTA_VECINOS_jun_id`) REFERENCES `JUNTA_VECINOS` (`jun_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `NOTICIA` ADD CONSTRAINT `NOTICIA_ACTIVIDAD_FK` FOREIGN KEY (`ACTIVIDAD_act_id`) REFERENCES `ACTIVIDAD` (`act_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `NOTICIA` ADD CONSTRAINT `NOTICIA_MIEMBRO_FK` FOREIGN KEY (`MIEMBRO_mie_rut`) REFERENCES `MIEMBRO` (`mie_rut`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `NOTICIA` ADD CONSTRAINT `NOTICIA_PROYECTO_FK` FOREIGN KEY (`PROYECTO_proy_id`) REFERENCES `PROYECTO` (`proy_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `PROYECTO` ADD CONSTRAINT `PROYECTO_ESTADO_PROYECTO_FK` FOREIGN KEY (`ESTADO_PROYECTO_est_proy_id`) REFERENCES `ESTADO_PROYECTO` (`est_proy_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `PROYECTO` ADD CONSTRAINT `PROYECTO_MIEMBRO_FK` FOREIGN KEY (`MIEMBRO_mie_rut`) REFERENCES `MIEMBRO` (`mie_rut`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `RESERVA` ADD CONSTRAINT `RESERVA_ESPACIO_FK` FOREIGN KEY (`ESPACIO_esp_id`) REFERENCES `ESPACIO` (`esp_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `RESERVA` ADD CONSTRAINT `RESERVA_MIEMBRO_FK` FOREIGN KEY (`MIEMBRO_mie_rut`) REFERENCES `MIEMBRO` (`mie_rut`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `SOLICITUD_CERTIFICADO` ADD CONSTRAINT `SOLICITUD_CERTIFICADO_CERTIFICADO_FK` FOREIGN KEY (`CERTIFICADO_cer_id`) REFERENCES `CERTIFICADO` (`cer_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `SOLICITUD_CERTIFICADO` ADD CONSTRAINT `SOLICITUD_CERTIFICADO_MIEMBRO_FK` FOREIGN KEY (`MIEMBRO_mie_rut`) REFERENCES `MIEMBRO` (`mie_rut`) ON DELETE NO ACTION ON UPDATE NO ACTION;
